### ISSUE TITLE
SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by SamsadSajid** [joe-jordan/pyvoro#19]
Got the following error while installing the library
```
Traceback (most recent call last):
  File "weighted_voro.py", line 1, in <module>
    import pyvoro
  File "/home/shamsad/Documents/garbage/thesis_simulation/lib/python3.5/site-packages/pyvoro/__init__.py", line 1, in <module>
    import voroplusplus
  File "voroplusplus.pyx", line 36, in init pyvoro.voroplusplus (pyvoro/voroplusplus.cpp:2696)
SystemError: Parent module '' not loaded, cannot perform relative import
```

Don't know what's wrong!

System config:
```
64bit architecture
Ubuntu 16.04
```

**Comment by liangtianumich** [comment]
Did you use python 3 instead of python 2:
https://github.com/Kitt-AI/snowboy/issues/316
use python 2 should work

**Comment by SamsadSajid** [comment]
will take a look.. thanks
