### ISSUE TITLE
TypeError: Extension constructor got multiple values for keyword argument 'sources'

### ISSUE THREAD

**Issue by akakcolin** [joe-jordan/pyvoro#2]
Hi,joe

I get the following error when building the pyvoro.

running build
running build_py
('missing cimport', 'pyvoro/voroplusplus.pyx')
libcpp.vector
    cython.operator
/usr/lib/pymodules/python2.7/Cython/Includes/libcpp/vector.pxd
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    packages=["pyvoro"],
  File "/usr/local/lib/python2.7/dist-packages/cb/**init**.py", line 262, in wrapped
    build(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cb/**init**.py", line 237, in build
    _seperate_build(e, global_macros, global_includes)
  File "/usr/local/lib/python2.7/dist-packages/cb/__init__.py", line 98, in _seperate_build
    _custom_cythonise(extension['sources'])
  File "/usr/local/lib/python2.7/dist-packages/cb/__init__.py", line 29, in _custom_cythonise
    e = cythonize(f)[0]
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 456, in cythonize
    aliases=aliases)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 440, in create_extension_list
    **kwds))
TypeError: Extension constructor got multiple values for keyword argument 'sources'

**Comment by joe-jordan** [comment]
What version of Cython are you using? just run `cython -V` at a terminal to see.

**Comment by akakcolin** [comment]
I used Cython 0.14.1, Now I update it to 0.19.1, everything is ok. Thank you very much
