### ISSUE TITLE
Throws `RecursionError` on initial import

### ISSUE THREAD

**Issue by msbc** [joe-jordan/pyvoro#20]
On initial import, a `RecursionError` is thrown. I have tried both installing `pyvoro` with `pip install pyvoro` and cloning and installing with `python setup.py install --user`. Both give the same result (see below).

System info:

    System Version: macOS 10.14.6 (18G87)
    Kernel Version: Darwin 18.7.0
    gcc version 9.2.0 (Homebrew GCC 9.2.0)
    Cython version 0.29.13
    Python 3.7.3

Error:

    Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
    [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pyvoro
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "$~/software/pyvoro/pyvoro/__init__.py", line 1, in <module>
        import voroplusplus
      File "voroplusplus.pyx", line 36, in init pyvoro.voroplusplus (pyvoro/voroplusplus.cpp:2696)
      File "<frozen importlib._bootstrap>", line 980, in _find_and_load
    RecursionError: maximum recursion depth exceeded

**Comment by joel-simon** [comment]
Manually installing from the feature/python3 branch fixed this error for me on python3.6.

**Comment by Gaozmmm** [comment]
> On initial import, a `RecursionError` is thrown. I have tried both installing `pyvoro` with `pip install pyvoro` and cloning and installing with `python setup.py install --user`. Both give the same result (see below).
> 
> System info:
> 
> ```
> System Version: macOS 10.14.6 (18G87)
> Kernel Version: Darwin 18.7.0
> gcc version 9.2.0 (Homebrew GCC 9.2.0)
> Cython version 0.29.13
> Python 3.7.3
> ```
> 
> Error:
> 
> ```
> Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
> [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyvoro
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "$~/software/pyvoro/pyvoro/__init__.py", line 1, in <module>
>     import voroplusplus
>   File "voroplusplus.pyx", line 36, in init pyvoro.voroplusplus (pyvoro/voroplusplus.cpp:2696)
>   File "<frozen importlib._bootstrap>", line 980, in _find_and_load
> RecursionError: maximum recursion depth exceeded
> ```

Hi, did you solve your problem? I encounter the same issue while using python 3.7

**Comment by liangtianumich** [comment]
pip install pyvoro will install the default master branch for pyvoro for python 2.7.  If you are using python 3.X, you should use the branch for python 3 feature branch by git checkout feature/python3 .

**Comment by kip-hart** [comment]
Why doesn't the version on PyPI support python 3, when 2 has been deprecated?

**Comment by liangtianumich** [comment]
The owner's last commit is 2014 for mainstream python 2.X and did not maintain after that. he gave a patch for python 3.X thinking some people may need it.

**Comment by kip-hart** [comment]
Ok, I've been using pyvoro from https://pypi.org/project/pyvoro-mmalahe/ without issues. Posting the link here in case other users need to make pyvoro a package dependency.
